import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/layouts/Header'
import { ProvidersRedux } from '@/store/provider'





export const metadata: Metadata = {
  title: 'Детский Сайт',
  description: 'Generated by create next app',
  icons: "/mainlogo.png",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <ProvidersRedux>
        <body><Header />{children}</body>
      </ProvidersRedux>
    </html>
  )
}
